site_name: My Dev Knowledge Base
site_url: https://juliamen.github.io/devNotes/

nav: 
 - Home : index.md
 - Salesforce :
   - Formstack : Salesforce/Formstack.md
   - JSON-to-SObject : Salesforce/JSON-to-SObject.md
   - SobjectChangeHandler : Salesforce/SobjectChangeHandler.md
   - VirtualRemoteAssistant : Salesforce/VirtualRemoteAssistant.md
   - gitFlow : Salesforce/gitFlow.md
   - parseDate : Salesforce/parseDate.md
 - Mulesoft : 
   - ArchitectHLD : Mulesoft/ArchitectHLD.md 
   - ArchitectLLD : Mulesoft/ArchitectLLD.md
   - APIGatewayAutodiscovery : Mulesoft/APIGatewayAutodiscovery.md
   - APILedArchitecture : Mulesoft/APILedArchitecture.md
   - AzureKeyVault : Mulesoft/AzureKeyVault.md
   - AnypointSecureAPI : Mulesoft/AnypointSecureAPI.md
   - ObjectStore : Mulesoft/ObjectStore.md
   - ObjectStoreLock : Mulesoft/ObjectStoreLock.md
   - Routing : Mulesoft/Routing.md
   - SQLPagination : Mulesoft/SQLPagination.md
   - VMQueueObjectStoreComparison : Mulesoft/VMQueueObjectStoreComparison.md
   - VMQueues : Mulesoft/VMQueues.md
   - VirtualPrivateSpaceVPN : Mulesoft/VirtualPrivateSpaceVPN.md
   - cachingObjStore : Mulesoft/cachingObjStore.md
   - dataMasking : Mulesoft/dataMasking.md
   - envVariables : Mulesoft/envVariables.md
   - projectSetup : Mulesoft/projectSetup.md
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
